//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoIntegrador.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancodedadosEntities : DbContext
    {
        public bancodedadosEntities()
            : base("name=bancodedadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<dadosseguranca> dadosseguranca { get; set; }
        public virtual DbSet<followusuario> followusuario { get; set; }
        public virtual DbSet<mensagem> mensagem { get; set; }
        public virtual DbSet<notificacao> notificacao { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<sobre> sobre { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuariomensagem> usuariomensagem { get; set; }
    }
}
